# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e19b63444901ce38b565367124f03539b27daed023fbf0e0f73d52a081e3c5c9f24db7eb669caf04d05ec640e12d0b3f6beb19cdc0556cd7ad9b944262432390

test:
  secret_key_base: 185ac1f8fba44f9697c316b3b872213f7cf85127d73edf2cc0f7bbe63c304f1691737beddc4044f27d61dc99eb538c0b7d7f62644e24df72c927a7a4cd4d9102

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
